
### Codd's Twelve Principles of Relational Databases:

.f6[

1. Information is represented logically in *tables*
2. Data must be *logically accessible* by table, primary key, and column.
3. *Null* values must be uniformly treated as “missing information,” not as empty strings, blanks, or zeros.
4. Metadata (data about the database) must be stored in the database just as regular data is
5. A single language must be able to define data, views, integrity
constraints, *authorization*, *transactions*, and data manipulation
6. *Views* must show the updates of their *base tables* and vice versa
7. A single operation must be available to do each of the following
operations: retrieve data, insert data, update data, or delete data
8. Batch and end-user operations are *logically separate* from physical
storage and access methods
9. Batch and end-user operations can change the database schema without having to recreate it or the applications built upon it
10. *Integrity* constraints must be available and stored in the metadata, not in
an application program
11. The data manipulation language of the relational system should not care
where or how the physical data is distributed and should not require
alteration if the physical data is centralized or distributed
12. Any *row processing* done in the system must obey the same *integrity rules* and *constraints* that set-processing operations do

]

