---
title: "TBA"
subtitle: "DASK Master II, MIDS & M2MO"
author: "Stéphane Boucheron"
institute: "Université de Paris"
date: "2020/11/20 (updated: `r Sys.Date()`)"
params:
  title: "TBA"
  curriculum: "Master II MIDS & M2MO"
  coursetitle: "Données massives"
  lecturer: "Stéphane Boucheron"
  homepage: "http://stephane-v-boucheron.fr/courses/mmd/"
  curriculum_homepage: "https://master.math.univ-paris-diderot.fr/annee/m1-mi/"
output:
  xaringan::moon_reader:
    css: ["header-footer.css",  "xaringan-themer.css", "custom-callout.css"]
    lib_dir: libs
    seal: false
    nature:
      nature:
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
name: inter-slide
class: left, middle, inverse

{{ content }}

---
name: layout-general
layout: true
class: left, middle

```{r setup, child="loaders_fixers.Rmd", echo=FALSE, message=FALSE, warning=FALSE}

```


---

```{r child='title_slide.Rmd'}

```



---
template: inter-slide

### `r fontawesome::fa("map", fill="white")`

### TBA 


---

### TBA 


---


```{r child="closing_slide.Rmd"}

```
