



### Agenda Semestre II  202-23


| Semaine(s) | Date(s) | Activité  |
|:----------:|:--------|:----------|
| .red[`r lubridate::isoweek(lubridate::as_date("2023-01-16"))`-`r lubridate::isoweek(lubridate::as_date("2023-02-24"))`] | `r lubridate::as_date("2023-01-16")`/`r lubridate::as_date("2023-02-24")`| Semestre II/Période I |
| `r lubridate::isoweek(lubridate::as_date("2023-02-27"))`| `r lubridate::as_date("2023-02-25")`/`r lubridate::as_date("2023-03-05")` | _Vacances Hiver_ |
| `r lubridate::isoweek(lubridate::as_date("2023-03-06"))` | `r lubridate::as_date("2023-03-06")`/`r lubridate::as_date("2023-03-10")`| **Examens Semestre II Pér. I** |
| `r lubridate::isoweek(lubridate::as_date("2023-03-13"))`-`r lubridate::isoweek(lubridate::as_date("2023-04-21"))` | `r lubridate::as_date("2023-03-13")`/`r lubridate::as_date("2023-04-24")`| Semestre II/Période II |
| `r lubridate::isoweek(lubridate::as_date("2023-04-24"))`-`r lubridate::isoweek(lubridate::as_date("2023-05-01"))` | `r lubridate::as_date("2024-04-22")`/`r lubridate::as_date("2023-05-07")`| _Vacances de Printemps_ |
| `r lubridate::isoweek(lubridate::as_date("2023-05-09"))`-`r lubridate::isoweek(lubridate::as_date("2023-05-23"))` | `r lubridate::as_date("2023-05-09")`/`r lubridate::as_date("2023-05-27")`| **Examens Semestre II Pér. II** |
| `r lubridate::isoweek(lubridate::as_date("2023-06-07"))` | | _Jury Session I_ |

--

`r fontawesome::fa("triangle-exclamation")` Presque tous les cours/UE sont organisés sur une période de 6 semaines 

Durant chaque *période*, vous suivez deux UE (6 ECTS)

Pour valider les 30 ECTS semestriels, vous choisissez (en général) une UE semestrielle 

